In [1]:
import pandas as pd
import talib as ta

In [2]:
%store -r df

In [3]:
df

,close,low,high,dollar_volume,upper,lower,log_ret,mom1,mom2,mom3,...,autocorr_4,autocorr_5,log_t1,log_t2,log_t3,log_t4,log_t5,short_sma,long_sma,sma
date_time,,,,,,,,,,,,,,,,,,,,,
2018-01-01 00:11:11.241,13763.5,13675.0,13920.0,9.339762e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:27:14.652,13775.5,13596.0,13789.5,9.340538e+06,13778.105281,13761.134719,0.000871,0.000872,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:48:23.395,13745.0,13657.0,13780.5,9.345154e+06,13776.618096,13745.547749,-0.002217,-0.002214,-0.001344,NaN,...,NaN,NaN,0.000871,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 01:09:43.777,13555.5,13555.5,13770.0,9.341081e+06,13812.138803,13600.987536,-0.013883,-0.013787,-0.015970,-0.015112,...,NaN,NaN,-0.002217,0.000871,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 01:32:03.253,13650.5,13550.0,13737.5,9.420639e+06,13788.546756,13600.325157,0.006984,0.007008,-0.006875,-0.009074,...,NaN,NaN,-0.013883,-0.002217,0.000871,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-04-30 22:56:45.216,5271.0,5264.5,5273.0,9.345586e+06,5269.720812,5222.823670,-0.000379,-0.000379,-0.002083,0.000190,...,-0.423297,0.253794,-0.001705,0.002274,-0.000095,0.000000,0.001804,5271.142857,5257.233333,1.0
2019-04-30 23:06:44.670,5270.0,5270.0,5275.5,9.349355e+06,5270.653095,5223.752387,-0.000190,-0.000190,-0.000569,-0.002272,...,-0.423906,0.220373,-0.000379,-0.001705,0.002274,-0.000095,0.000000,5272.428571,5259.900000,1.0
2019-04-30 23:14:24.220,5263.5,5263.5,5270.0,9.346254e+06,5271.048855,5224.634844,-0.001234,-0.001233,-0.001423,-0.001802,...,-0.406440,0.221755,-0.000190,-0.000379,-0.001705,0.002274,-0.000095,5271.428571,5262.100000,1.0
2019-04-30 23:21:57.227,5257.5,5257.0,5266.0,9.353580e+06,5271.046709,5225.394492,-0.001141,-0.001140,-0.002372,-0.002561,...,-0.368961,0.179785,-0.001234,-0.000190,-0.000379,-0.001705,0.002274,5269.571429,5263.900000,1.0
2019-04-30 23:34:40.947,5256.5,5256.5,5262.5,9.393172e+06,5270.978162,5226.112403,-0.000190,-0.000190,-0.001330,-0.002562,...,-0.371007,0.208220,-0.001141,-0.001234,-0.000190,-0.000379,-0.001705,5267.642857,5264.666667,1.0

In [4]:
df['rsi'] = ta.RSI(df.close.values)
df['willr'] = ta.WILLR(df.close.values, df.high.values, df.low.values)
df['macd'], _, _ = ta.MACD(df.close.values)
df['proc'] = ta.ROC(df.close.values)
df['obv'] = ta.OBV(df.close.values, df.dollar_volume.values)

In [5]:
df

,close,low,high,dollar_volume,upper,lower,log_ret,mom1,mom2,mom3,...,log_t4,log_t5,short_sma,long_sma,sma,rsi,willr,macd,proc,obv
date_time,,,,,,,,,,,,,,,,,,,,,
2018-01-01 00:11:11.241,13763.5,13675.0,13920.0,9.339762e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.339762e+06
2018-01-01 00:27:14.652,13775.5,13596.0,13789.5,9.340538e+06,13778.105281,13761.134719,0.000871,0.000872,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.868030e+07
2018-01-01 00:48:23.395,13745.0,13657.0,13780.5,9.345154e+06,13776.618096,13745.547749,-0.002217,-0.002214,-0.001344,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.335146e+06
2018-01-01 01:09:43.777,13555.5,13555.5,13770.0,9.341081e+06,13812.138803,13600.987536,-0.013883,-0.013787,-0.015970,-0.015112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.934987e+03
2018-01-01 01:32:03.253,13650.5,13550.0,13737.5,9.420639e+06,13788.546756,13600.325157,0.006984,0.007008,-0.006875,-0.009074,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.414704e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-04-30 22:56:45.216,5271.0,5264.5,5273.0,9.345586e+06,5269.720812,5222.823670,-0.000379,-0.000379,-0.002083,0.000190,...,0.000000,0.001804,5271.142857,5257.233333,1.0,62.281316,-38.888889,9.470610,0.438262,-5.215838e+09
2019-04-30 23:06:44.670,5270.0,5270.0,5275.5,9.349355e+06,5270.653095,5223.752387,-0.000190,-0.000190,-0.000569,-0.002272,...,-0.000095,0.000000,5272.428571,5259.900000,1.0,61.397110,-26.666667,9.261199,0.323625,-5.225188e+09
2019-04-30 23:14:24.220,5263.5,5263.5,5270.0,9.346254e+06,5271.048855,5224.634844,-0.001234,-0.001233,-0.001423,-0.001802,...,0.002274,-0.000095,5271.428571,5262.100000,1.0,55.847089,-50.000000,8.473071,0.028506,-5.234534e+09
2019-04-30 23:21:57.227,5257.5,5257.0,5266.0,9.353580e+06,5271.046709,5225.394492,-0.001141,-0.001140,-0.002372,-0.002561,...,-0.001705,0.002274,5269.571429,5263.900000,1.0,51.242415,-74.626866,7.280400,-0.076024,-5.243887e+09
2019-04-30 23:34:40.947,5256.5,5256.5,5262.5,9.393172e+06,5270.978162,5226.112403,-0.000190,-0.000190,-0.001330,-0.002562,...,-0.000379,-0.001705,5267.642857,5264.666667,1.0,50.495139,-94.444444,6.183232,-0.085535,-5.253281e+09

In [6]:
%store df

Stored 'df' (DataFrame)